# Custom Language File for Launcher Customizer

[ejs.app]
title = "OneLords Launcher"

[ejs.landing]
mediaGitHubURL = "https://onelords.fr"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.onelords.fr"

[ejs.settings]
sourceGithubLink = "https://github.com/Plhume/OneLords-Launcher"
supportLink = "https://github.com/Plhume/OneLords-Launcher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur OneLords !"
welcomeDescription = "OneLords est un serveur Minecraft français. Nous innovons avec la création d'un mode de jeu inédit, le Skylands, qui vous plonge dans un univers sur des îles volantes, propulsées par l'exploration et une économie fiable et travailée."
welcomeDescCTA = "Vous arrivez bientôt sur OneLords !"
