[ejs.landing]
updateAvailableTooltip = "Mise-à-jour disponible !"
usernamePlaceholder = "Pseudo"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "Serveur"
serverStatusPlaceholder = "❌"
mojangStatus = "Statut Mojang"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essentiel"
newsButton = "Actualités"
launchButton = "Lancer"
launchButtonPlaceholder = "&#8226; Pas de serveur défini"
launchDetails = "Patientez..."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Chargement des actualités..."
newsErrorFailedSpan = "Impossible de récupérer les actualités"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Pas d'actualités"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "Connexion à Minecraft"
loginEmailError = "* Valeurs invalides"
loginEmailPlaceholder = "Email ou pseudo"
loginPasswordError = "* Obligatoire"
loginPasswordPlaceholder = "Mot de passe"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "Mot de passe oublié ?"
loginRememberMeText = "Se souvenir de moi ?"
loginButtonText = "Se connecter"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte ?"
loginPasswordDisclaimer1 = "Les identifiants sont directements envoyés à Mojang et ne sont pas sauvegardés."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Connexion avec Microsoft"
loginWithMojang = "Connexion avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs"
serverSelectConfirm = "Selectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Choisir un compte"
accountSelectConfirm = "Selectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Informations"
navUpdates = "Mises-à-jours"
navDone = "Terminer"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajouter un compte ou gérer celui existant."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres de jeu"
minecraftTabHeaderDesc = "Options relatives au jeu lancé."
gameResolutionTitle = "Résolution de la fenêtre"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Se connecter automatiquement au serveur."
launchDetachedTitle = "Lancer le jeu séparément du launcher."
launchDetachedDesc = "Si le jeu n'est pas détaché, fermer le launcher fermera automatiquement le jeu."
tabModsHeaderText = "Paramètres des mods"
tabModsHeaderDesc = "Activer ou désactiver des mods."
switchServerButton = "Changer"
requiredMods = "Mods requis"
optionalMods = "Mods optionnels"
dropinMods = "Glisser-déposer les mods"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = "Packs de shaders"
shaderpackDesc = "Activer ou désactiver les shaders. A noter que les shaders dégradent les performances du jeu et qu'ils ne sont pas obligatoires."
selectShaderpack = "Selectionner un shader"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérer les options relatives à Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM Maximum"
minRAM = "RAM Minimum"
memoryDesc = "Pour de meilleures performances, nous vous conseillons 3Go de RAM. Définir la RAM maximum et minimum au même niveau peut aider à réduire les lags."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Executable Java"
javaExecSelDialogTitle = "Selectionner un executable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L'executable Java est vérifié avant le lancement du jeu."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options additionnelles JVM"
jvmOptsDesc = "Options à fournir à la JVM au moment de l'exécution. <em>-Xms</em> et <em>-Xmx</em> ne doivent pas être inclus."
launcherTabHeaderText = "Paramètres du Launcher"
launcherTabHeaderDesc = "Options relatives au launcher."
allowPrereleaseTitle = "Autoriser les versions bêta."
allowPrereleaseDesc = "Les versions bêta sont des versions de tests, et peuvent contenir des bugs.<br>Ce sera toujours vrai si vous activer les version bêta."
dataDirectoryTitle = "Dossier de répertoire"
selectDataDirectory = "Selectionner un dossier de répertoire"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers de jeu et les installations Java locales seront stockés dans le répertoire data.<br>Les captures d'écran et les sauvegardes du monde sont stockées dans le dossier instance de la configuration serveur correspondante."
aboutTabHeaderText = "Informations"
aboutTabHeaderDesc = "Afficher les informations sur le launcher."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Soutenir"
devToolsConsole = "Console des développeurs"
releaseNotes = "Notes de version"
changelog = "Mises-à-jours"
noReleaseNotes = "Pas de notes de version"
viewReleaseNotes = "Voir les notes de version sur Github"
launcherUpdatesHeaderText = "Mises-à-jour du launcher"
launcherUpdatesHeaderDesc = "Télécharger et installer les nouvelles versions du launcher."
checkForUpdates = "Trouver des versions !"
whatsNew = "Quoi de nouveau ?"
updateReleaseNotes = "Mises-à-jours des notes de version"

[ejs.waiting]
waitingText = "Attente de Microsoft..."

[ejs.welcome]
continueButton = "Continuer"


[js.discord]
waiting = "Attente du client..."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "Connexion"
loggingIn = "Se connecter"
success = "Réussi !"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue dans la connexion !"
desc = "Une erreur inconnue est survenue !"

[js.landing.launch]
pleaseWait = "Patientez.."
failureTitle = "Erreur dans le lancement !"
failureText = "Voir la console (CTRL + Shift + i) pour plus de détails."
okay = "Ok"
maintenance = "Maintenance en cours !"

[js.landing.selectedAccount]
noAccountSelected = "Pas de comptes selectionné !"

[js.landing.selectedServer]
noSelection = "Pas de serveur selectionné !"
loading = "Chargement..."

[js.landing.serverStatus]
server = "Serveur"
offline = "❌"
players = "Joueurs"

[js.landing.systemScan]
checking = "Vérification des informations du système..."
noCompatibleJava = "Aucune installation compatible<br>Java n'a été trouvée"
installJavaMessage = "Pour lancer Minecraft, vous devez disposer d'une installation 64 bits de Java {major}. Voulez-vous que nous en installions une copie ?"
installJava = "Installer Java"
installJavaManually = "Installer amnuellement"
javaDownloadPrepare = "Préparation du téléchargement..."
javaDownloadFailureTitle = "Erreur dans le téléchargement de Java !"
javaDownloadFailureText = "Voir la console (CTRL + Shift + i) pour plus de détails."
javaRequired = "Java est requis <br>pour jouer !"
javaRequiredMessage = 'A valid x64 installation of Java {major} is required to launch.<br><br>Please refer to our <a href="https://github.com/Plhume/OneLords-Launcher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Java Management Guide</a> for instructions on how to manually install Java.'
javaRequiredDismiss = "Je comprend"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Impossible de trouver une distribution d'OpenJDK."
javaDownloadCorruptedError = "Le JDK téléchargé a un mauvais hachage, le fichier peut être corrompu."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Connexion..."
fatalError = "Erreur !"
unableToLoadDistributionIndex = "Impossible de charger une copie de l'index de distribution. Voir la console (CTRL + Shift + i) pour plus de détails."
pleaseWait = "Patientez..."
errorDuringLaunchTitle = "Erreur dans le lancement !"
seeConsoleForDetails = "Voir la console (CTRL + Shift + i) pour plus de détails."
validatingFileIntegrity = "Vérification..."
errorDuringFileVerificationTitle = "Erreur dans la vérification de l'intégrité des fichiers !"
downloadingFiles = "Téléchargement..."
errorDuringFileDownloadTitle = "Erreur dans le téléchargement des fichiers !"
preparingToLaunch = "Préparation..."
launchingGame = "Lancement..."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, ne s'est pas téléchargé correctement. Par conséquent le jeu ne peut pas se lancer.<br><br>Pour corriger cette erreur, désactivez temporairement votre anti-virus puis relancez le jeu.<br><br>Si vous avez le temps, regardez <a href=\"https://github.com/Plhume/OneLords-Launcher/issues\">soumettre un problème</a> et indiquez-nous le logiciel antivirus que vous utilisez. Nous les contacterons pour tenter de résoudre le problème."
doneEnjoyServer = "Bienvenue ❤️"
checkConsoleForDetails = "Merci de regarder la console (CTRL + Shift + i) pour plus de détails."

[js.landing.news]
checking = "Chargement des nouvelles"

[js.landing.discord]
loading = "Chargement du jeu..."
joining = "Direction OneLords !"
joined = "Explorer les nouvelles îles !"

[js.overlay]
dismiss = "Cacher"

[js.settings.fileSelectors]
executables = "Exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Quelque chose n'a pas bien fonctionné ?"
errorMessage = "La connexion à Microsoft à échouée, réessayez plus tard !"
okButton = "Ok"

[js.settings.mstfLogout]
errorTitle = "Quelque chose n'a pas bien fonctionné ?"
errorMessage = "La connexion à Microsoft à échouée, réessayez plus tard !"
okButton = "Ok"

[js.settings.authAccountSelect]
selectButton = "Selectionnez un compte"
selectedButton = "Selectionnez un compte &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>Ceci est Votre Dernier Compte"
lastAccountWarningMessage = "Pour utiliser le lanceur, vous devez être connecté à au moins un compte. Vous devrez vous connecter à nouveau après.<br><br>Êtes vous sûr de vous déconnecter ?"
confirmButton = "Oui !"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Pseudo"
uuid = "UUID"
selectAccount = "Selectionner un compte"
selectedAccount = "Selectionner un compte ✓"
logout = "Déconnexion"

[js.settings.dropinMods]
removeButton = "Supprimer"
deleteFailedTitle = "Échec de la suppression<br>Glissez-déposez le mod {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n'est pas utilisé et réessayez."
failedToggleTitle = "Impossible de changer<br>Un ou plusieurs mods"
okButton = "Ok"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Selectionné : Java {version} ({vendor})"
invalidSelection = "Sélection invalide"
requiresJava = "Java requis {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Versions Bêta"
stableReleaseTitle = "Verison stable"
releaseNotesFailed = "Impossible de récupérer les versions."

[js.settings.updates]
newReleaseTitle = "Nouvelles version disponible !"
newPreReleaseTitle = "Nouvelles version bêta disponible !"
downloadingButton = "Téléchargement..."
downloadButton = 'Télécharger depuis GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermez le lanceur et exécutez le dmg pour mettre à jour..</span>'
latestVersionTitle = "Vous utilisez la dernière version !"
checkForUpdatesButton = "Vérifiez les mises-à-jours"
checkingForUpdatesButton = "vérification des mises-à-jours..."

[js.settings.msftLogin]
errorTitle = "Connexion à Microsoft impossible !"
errorMessage = "Nous ne parvenons pas à nous connecter aux serveurs de Microsoft, réessayez plus tard."
okButton = "Ok"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale : Impossible de charger l'index de distribution"
fatalErrorMessage = "La connexion entre les serveurs et l'index de distribution n'a pas pu être établie. Aucune copie locale n'a pu être utilisée. <br><br>L'index de distribution est essentiel, c'est ce qui permet de récupérer toutes les informations sur les serveurs de jeu. Soyez sûr d'être connecté à internet, puis relancer le launcher."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Impossible de recharger la connexion"
failedMessage = "Nous ne parvenons pas à recharger la connexion de <strong>{account}</strong>. Merci de choisir un autre compte puis réessayez."
failedMessageSelectAnotherAccount = "Nous ne parvenons pas à nous connecter à <strong>{account}</strong>. Connectez vous plus tard."
loginButton = "Connexion"
selectAnotherAccountButton = "Selectionner un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Recherche de mises-à-jours..."
installNowButton = "Installer maintenant !"
checkForUpdatesButton = "Rechercher les msies-à-jours"

[js.auth.microsoft.error]
noProfileTitle = "Erreur dans la connexion :<br>Pas de profile selectionné"
noProfileDesc = "Votre compte Microsoft n'est pas lié à Minecraft. Si vous avez récemment acheté ou récupéré le jeu par le Xbox Game Pass, rendez-vous vers <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si vous avez acheté le jeu, rendez-vous vers <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erreur dans la connexion :<br>Pas de compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft et votre compte Xbox ne sont pas liés."
xblBannedTitle = "Erreur dans la connexion :<br>Serveurs d'Xbox injoignables"
xblBannedDesc = "Votre compte Microsoft vient d'une région bannie par les services Xbox."
under18Title = "Erreur dans la connexion :<br>Accord parental requis"
under18Desc = "Les comptes d'un propriétaire mineur doivent être activés par l'accord parental."
unknownTitle = "Erreur inconnue dans la connexion !"
unknownDesc = "Une erreur inconnue est survenue, vérifiez les informations puis réessayez."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne :<br>Méthode invalide"
methodNotAllowedDesc = "La méthode n'est pas autorisée, merci de reporter cette erreur."
notFoundTitle = "Erreur interne :<br>Inconnue"
notFoundDesc = "La connexion n'a pas été approuvée, merci de reporter cette erreur."
accountMigratedTitle = "Erreur dans la connexion :<br>Compte migré"
accountMigratedDesc = "Vous avez essayé de vous connecter avec un compte migré. Essayez en utilisant l'adresse mail de votre compte."
invalidCredentialsTitle = "Erreur dans la connexion :<br>Identifiants incorrects"
invalidCredentialsDesc = "L'email ou le mot de passe que vous avez entré est incorrecte, réessayez."
tooManyAttemptsTitle = "Erreur dans la connexion :<br>Trop de demandes !"
tooManyAttemptsDesc = "Nous avons trop de demandes de connexion, réessayez plus tard."
invalidTokenTitle = "Erreur dans la connexion :<br>Token invalide"
invalidTokenDesc = "Le token d'accès est invalide, réessayez."
tokenHasProfileTitle = "Erreur dans la connexion :<br>Le token a un profil."
tokenHasProfileDesc = "Le token d'accès à déjà été activé, réessayez avec un autre token."
credentialsMissingTitle = "Erreur dans la connexion :<br>Identifiants manquants"
credentialsMissingDesc = "Pseudo/mot de passe n'ont pas été envoyés, ou le mot de passe est de moins de 3 caractères."
invalidSaltVersionTitle = "Erreur dans la connexion :<br>Version de connexion invalide"
invalidSaltVersionDesc = "La version de connexion est invalide."
unsupportedMediaTypeTitle = "Erreur interne :<br>Unsupported Media Type"
unsupportedMediaTypeDesc = "Le type de média demandé n'est plus supportés, merci de reporter cette erreur."
accountGoneTitle = "Erreur dans la connexion :<br>Compte migré"
accountGoneDesc = "Votre compte a été migré, connectez vous avez un compte Microsoft."
unreachableTitle = "Erreur dans la connexion :<br>Injoignable"
unreachableDesc = "Nous ne parvenons pas à joindre les serveurs de connexions. Vérifiez qu'ils sont en ligne et que vous êtes connecté à internet."
gameNotPurchasedTitle = "Erreur dans la connexion :<br>Jeu n'ont payé"
gameNotPurchasedDesc = "Vous tentez de vous connecter avec une copie de Minecraft, achetez le jeu à l'adresse <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Erreur inconnue dans la connexion"
unknownErrorDesc = "Une erreur inconnue est survenue lors de la connexion, vérifiez la console pour plus de détails."
